lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 1800
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
            # encryption algorithm used by the encoder service
        signature_algorithm: RS256
